version: '3.8'

services:
    backend:
        container_name: backend
        build:
            context: ./backend
        volumes:
            - ./backend:/backend
        command: python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 wsgi:application
        ports:
            - 8000:8000
        restart: always
    nginx:
        build: ./nginx
        volumes:
            - ./backend:/backend
        ports:
          - "80:80"
        depends_on:
          - backend
    frontend:
        container_name: frontend
        env_file:
            - ./frontend/.env
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        command: serve -s build
        ports:
            - 3000:3000
        depends_on:
            - backend
        restart: always
