# Generated by Django 4.1.2 on 2022-11-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_collectionphoto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='photo',
        ),
        migrations.AlterUniqueTogether(
            name='collectionphoto',
            unique_together={('photo', 'collection')},
        ),
        migrations.AddField(
            model_name='keyword',
            name='photo',
            field=models.ManyToManyField(to='images.photo'),
        ),
    ]
