# Generated by Django 4.1.2 on 2022-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_keyword_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='photo',
            new_name='photos',
        ),
        migrations.RemoveField(
            model_name='color',
            name='photo',
        ),
        migrations.AddField(
            model_name='color',
            name='photos',
            field=models.ManyToManyField(to='images.photo'),
        ),
        migrations.DeleteModel(
            name='Conversion',
        ),
    ]
