# Generated by Django 4.1.2 on 2022-11-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_rename_photo_keyword_photos_remove_color_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='ai_score',
        ),
    ]
