# Generated by Django 4.1.2 on 2022-11-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_keyword_ai_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='keyword',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='color',
            name='green',
        ),
        migrations.RemoveField(
            model_name='color',
            name='hex',
        ),
        migrations.RemoveField(
            model_name='color',
            name='red',
        ),
    ]
