# Generated by Django 4.1.2 on 2022-11-23 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0007_rename_keyword_color_color_remove_color_blue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePhoto',
            new_name='LikedPhoto',
        ),
        migrations.AddField(
            model_name='collection',
            name='photos',
            field=models.ManyToManyField(to='images.photo'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('title', 'user')},
        ),
        migrations.DeleteModel(
            name='CollectionPhoto',
        ),
    ]
