# Generated by Django 4.1.2 on 2022-11-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_rename_likephoto_likedphoto_collection_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photos',
            field=models.ManyToManyField(blank=True, to='images.photo'),
        ),
    ]
