# Generated by Django 4.1.2 on 2022-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_collection_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='photos',
            field=models.ManyToManyField(related_name='keywords', to='images.photo'),
        ),
    ]
