# Generated by Django 4.1.2 on 2022-11-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_keyword_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='photos',
            field=models.ManyToManyField(related_name='colors', to='images.photo'),
        ),
    ]
