# Generated by Django 4.1.2 on 2022-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='tone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
