# Generated by Django 4.1.2 on 2022-11-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_color_tone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='images.photo')),
                ('hex', models.CharField(max_length=6)),
                ('white', models.FloatField()),
                ('black', models.FloatField()),
                ('red', models.FloatField()),
                ('green', models.FloatField()),
                ('blue', models.FloatField()),
                ('cyan', models.FloatField()),
                ('magenta', models.FloatField()),
                ('yellow', models.FloatField()),
            ],
        ),
    ]
